function [mooddata, inputdata] = ssm_load_data(option)

    if option.group
  
        % load data 
        mooddata = importdata(sprintf('%s/data_prep/%s/mooddata_group_%s.csv', ...
                                option.filepath, ...
                                option.foldername, ...
                                option.filename)); % prepared data for ssm
        if option.input
            inputdata = importdata(sprintf('%s/data_prep/%s/inputdata_group_%s.csv', ...
                                option.filepath, ...
                                option.foldername, ...
                                option.filename)); % prepared input for ssm
        else
            inputdata = [];
        end
        
    else
        
        Nfiles = dir(sprintf('%s/data_prep/%s/mooddata_%s*', ...
                                    option.filepath, ...
                                    option.foldername, ...
                                    option.filename));
                                
        for sj = 1:length(Nfiles)
            mooddata{sj} = importdata(sprintf('%s/data_prep/%s/mooddata_%s%03d.csv', ...
                                    option.filepath, ...
                                    option.foldername, ...
                                    option.filename, sj)); % prepared data for ssm
            if option.input
                inputdata{sj} = importdata(sprintf('%s/data_prep/%s/inputdata_%s%03d.csv', ...
                                    option.filepath, ...
                                    option.foldername, ...
                                    option.filename, sj)); % prepared input for ssm
            else
                inputdata{sj} = [];
            end
            
        end

    end


end